[package]
name = "word-counter"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
anyhow = "=1"
cli-table = "=0.4"
config = "=0.11"
serde = { version = "=1", features = ["derive"] }
serde_json = "=1"
tracing = "=0.1"
tracing-subscriber = "=0.2"
